In [1]:
import pandas as pd
import os

In [2]:
# 1. Create a DataFrame Covid data(full csv). 
full_results_df1  = pd.read_csv('/Users/benjaminshelburn/Desktop/Classwork/Final Project/COVID-19_Case_Surveillance_Public_Use_Data_with_Geography.csv')
full_results_df1

/Users/benjaminshelburn/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,case_month,res_state,state_fips_code,res_county,county_fips_code,age_group,sex,race,ethnicity,case_positive_specimen_interval,case_onset_interval,process,exposure_yn,current_status,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
0,2020-12,AR,5.0,BOONE,5009.0,0 - 17 years,NaN,NaN,NaN,0.0,NaN,Missing,Missing,Laboratory-confirmed case,Symptomatic,Missing,Missing,NaN,NaN
1,2021-10,MO,29.0,PHELPS,29161.0,0 - 17 years,NaN,NaN,NaN,0.0,NaN,Missing,Missing,Laboratory-confirmed case,Missing,Unknown,Missing,Unknown,NaN
2,2020-10,MO,29.0,CASS,29037.0,0 - 17 years,Female,NaN,NaN,0.0,0.0,Missing,Missing,Laboratory-confirmed case,Symptomatic,Unknown,Missing,Unknown,NaN
3,2021-08,TN,47.0,CLAIBORNE,47025.0,0 - 17 years,Female,Missing,Missing,0.0,NaN,Missing,Missing,Laboratory-confirmed case,Missing,Missing,Missing,Missing,NaN
4,2020-11,GA,13.0,EFFINGHAM,13103.0,0 - 17 years,Female,Unknown,Missing,NaN,0.0,Missing,Missing,Laboratory-confirmed case,Symptomatic,Missing,Missing,Missing,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37532067,2020-11,SD,46.0,NaN,NaN,65+ years,Male,White,Unknown,NaN,0.0,Missing,Missing,Laboratory-confirmed case,Symptomatic,Missing,Missing,Missing,NaN
37532068,2020-11,SD,46.0,NaN,NaN,65+ years,Male,White,Unknown,NaN,0.0,Missing,Missing,Laboratory-confirmed case,Symptomatic,Missing,Missing,Missing,NaN
37532069,2020-11,SD,46.0,NaN,NaN,65+ years,Male,White,Unknown,NaN,0.0,Missing,Missing,Laboratory-confirmed case,Symptomatic,Missing,Missing,Missing,NaN
37532070,2020-11,SD,46.0,NaN,NaN,65+ years,Male,White,Unknown,NaN,0.0,Missing,Missing,Laboratory-confirmed case,Symptomatic,Missing,Missing,Missing,NaN
37532071,2020-11,SD,46.0,NaN,NaN,65+ years,Male,White,Unknown,NaN,0.0,Missing,Missing,Laboratory-confirmed case,Symptomatic,Missing,Missing,Missing,NaN

In [3]:
# Columns to drop
full_results_df2 = full_results_df1.drop(['case_month'], axis=1)
full_results_df2 = full_results_df2.drop(['state_fips_code'], axis=1)
full_results_df2 = full_results_df2.drop(['res_county'], axis=1)
full_results_df2 = full_results_df2.drop(['county_fips_code'], axis=1)
full_results_df2 = full_results_df2.drop(['ethnicity'], axis=1)
full_results_df2 = full_results_df2.drop(['process'], axis=1)
full_results_df2 = full_results_df2.drop(['case_positive_specimen_interval'], axis=1)
full_results_df2 = full_results_df2.drop(['case_onset_interval'], axis=1)
full_results_df2 = full_results_df2.drop(['current_status'], axis=1)
full_results_df2

,res_state,age_group,sex,race,exposure_yn,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
0,AR,0 - 17 years,NaN,NaN,Missing,Symptomatic,Missing,Missing,NaN,NaN
1,MO,0 - 17 years,NaN,NaN,Missing,Missing,Unknown,Missing,Unknown,NaN
2,MO,0 - 17 years,Female,NaN,Missing,Symptomatic,Unknown,Missing,Unknown,NaN
3,TN,0 - 17 years,Female,Missing,Missing,Missing,Missing,Missing,Missing,NaN
4,GA,0 - 17 years,Female,Unknown,Missing,Symptomatic,Missing,Missing,Missing,NaN
...,...,...,...,...,...,...,...,...,...,...
37532067,SD,65+ years,Male,White,Missing,Symptomatic,Missing,Missing,Missing,NaN
37532068,SD,65+ years,Male,White,Missing,Symptomatic,Missing,Missing,Missing,NaN
37532069,SD,65+ years,Male,White,Missing,Symptomatic,Missing,Missing,Missing,NaN
37532070,SD,65+ years,Male,White,Missing,Symptomatic,Missing,Missing,Missing,NaN
37532071,SD,65+ years,Male,White,Missing,Symptomatic,Missing,Missing,Missing,NaN

In [4]:
full_results_df2 = full_results_df2.dropna(how='any')
full_results_df2

,res_state,age_group,sex,race,exposure_yn,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
94,NH,18 to 49 years,Male,Multiple/Other,Missing,Symptomatic,No,Unknown,No,Yes
134,NC,18 to 49 years,Female,White,Missing,Symptomatic,No,Unknown,No,Yes
135,OH,18 to 49 years,Female,White,Yes,Symptomatic,No,Missing,No,Yes
136,CO,18 to 49 years,Female,White,Missing,Missing,No,Missing,Missing,Yes
147,IA,50 to 64 years,Male,White,Yes,Symptomatic,Yes,No,No,Yes
...,...,...,...,...,...,...,...,...,...,...
37475933,SD,50 to 64 years,Female,White,Yes,Symptomatic,Missing,Missing,Missing,Yes
37502839,SD,18 to 49 years,Male,White,Missing,Symptomatic,Missing,Missing,Missing,Yes
37523722,SD,18 to 49 years,Female,White,Missing,Symptomatic,Missing,Missing,Missing,Yes
37523727,SD,18 to 49 years,Female,White,Missing,Symptomatic,No,Missing,Missing,Yes
37530324,SD,50 to 64 years,Male,White,Missing,Symptomatic,Missing,Missing,Missing,Yes

In [5]:
# Remove "Unknown, nul, NA, Missing" values

full_results_df3 = full_results_df2.copy()
full_results_df3 = full_results_df2.loc[full_results_df2['age_group']!='Missing',:]
full_results_df3 = full_results_df3.loc[full_results_df3['age_group']!='NA',:]
full_results_df3 = full_results_df3.loc[full_results_df3['sex']!='Missing',:]
full_results_df3 = full_results_df3.loc[full_results_df3['sex']!='NA',:]
full_results_df3 = full_results_df3.loc[full_results_df3['sex']!='Unknown',:]
full_results_df3 = full_results_df3.loc[full_results_df3['race']!='Missing',:]
full_results_df3 = full_results_df3.loc[full_results_df3['race']!='NA',:]
full_results_df3 = full_results_df3.loc[full_results_df3['race']!='Unknown',:]
full_results_df3 = full_results_df3.loc[full_results_df3['exposure_yn']!='Missing',:]
full_results_df3 = full_results_df3.loc[full_results_df3['exposure_yn']!='Unknown',:]
full_results_df3 = full_results_df3.loc[full_results_df3['exposure_yn']!='Unknown',:]
full_results_df3 = full_results_df3.loc[full_results_df3['symptom_status']!='Missing',:]
full_results_df3 = full_results_df3.loc[full_results_df3['symptom_status']!='nul',:]
full_results_df3 = full_results_df3.loc[full_results_df3['symptom_status']!='Unknown',:]
full_results_df3 = full_results_df3.loc[full_results_df3['hosp_yn']!='Missing',:]
full_results_df3 = full_results_df3.loc[full_results_df3['hosp_yn']!='Unknown',:]
full_results_df3 = full_results_df3.loc[full_results_df3['icu_yn']!='Missing',:]
full_results_df3 = full_results_df3.loc[full_results_df3['icu_yn']!='nul',:]
full_results_df3 = full_results_df3.loc[full_results_df3['icu_yn']!='Unknown',:]
full_results_df3 = full_results_df3.loc[full_results_df3['death_yn']!='Missing',:]
full_results_df3 = full_results_df3.loc[full_results_df3['death_yn']!='NA',:]
full_results_df3 = full_results_df3.loc[full_results_df3['death_yn']!='Unknown',:]
full_results_df3

,res_state,age_group,sex,race,exposure_yn,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn
147,IA,50 to 64 years,Male,White,Yes,Symptomatic,Yes,No,No,Yes
197,OH,18 to 49 years,Female,Multiple/Other,Yes,Symptomatic,No,No,No,Yes
256,IA,0 - 17 years,Male,White,Yes,Symptomatic,No,No,No,Yes
537,KS,18 to 49 years,Female,White,Yes,Symptomatic,No,No,No,Yes
538,OH,18 to 49 years,Male,White,Yes,Symptomatic,No,No,No,Yes
...,...,...,...,...,...,...,...,...,...,...
37400468,NC,18 to 49 years,Male,White,Yes,Symptomatic,Yes,No,No,Yes
37401012,NC,65+ years,Male,White,Yes,Symptomatic,Yes,Yes,Yes,Yes
37424075,OK,18 to 49 years,Male,White,Yes,Symptomatic,No,No,No,No
37437398,OK,18 to 49 years,Female,White,Yes,Symptomatic,No,No,No,Yes
37455097,OK,18 to 49 years,Male,White,Yes,Symptomatic,No,No,No,Yes

In [6]:
# Does the exposure column only have "Yes?", then drop

exposure_counts = full_results_df3.exposure_yn.value_counts()
print(exposure_counts)

full_results_df3 = full_results_df3.drop(['exposure_yn'], axis=1)

Yes    222344
Name: exposure_yn, dtype: int64

In [7]:
# Make a copy of the df with the empty column "outcome"
results_df = full_results_df3.copy()

results_df["outcome"]=""
results_df

,res_state,age_group,sex,race,symptom_status,hosp_yn,icu_yn,death_yn,underlying_conditions_yn,outcome
147,IA,50 to 64 years,Male,White,Symptomatic,Yes,No,No,Yes,
197,OH,18 to 49 years,Female,Multiple/Other,Symptomatic,No,No,No,Yes,
256,IA,0 - 17 years,Male,White,Symptomatic,No,No,No,Yes,
537,KS,18 to 49 years,Female,White,Symptomatic,No,No,No,Yes,
538,OH,18 to 49 years,Male,White,Symptomatic,No,No,No,Yes,
...,...,...,...,...,...,...,...,...,...,...
37400468,NC,18 to 49 years,Male,White,Symptomatic,Yes,No,No,Yes,
37401012,NC,65+ years,Male,White,Symptomatic,Yes,Yes,Yes,Yes,
37424075,OK,18 to 49 years,Male,White,Symptomatic,No,No,No,No,
37437398,OK,18 to 49 years,Female,White,Symptomatic,No,No,No,Yes,
37455097,OK,18 to 49 years,Male,White,Symptomatic,No,No,No,Yes,

In [8]:
results_df.to_csv(r'/Users/benjaminshelburn/Desktop/FinalFinalFinal/MLCleanData.csv', index = False)